### ISSUE TITLE
Nuget Installation

### ISSUE THREAD

**Issue by charliethydog** [ChaseDRedmon/Cirrus#2]
Nuget gives the following error
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Cirrus 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by ChaseDRedmon** [comment]
Hi. This project targets .NET 5. Multi targeting for backwards compatibility is coming in the next minor release version, but is not currently supported. 

Version 1.2 is in beta and is a large rewrite of the library, which does contain breaking changes from version 1.1

If you want to want to use the library now, you have to update your project to target .NET 5 or greater.

**Comment by ChaseDRedmon** [comment]
Hi again,

After a bit of research on package dependencies, I won't be supporting .NET Framework 4.6.1 or earlier as it is not built on .NET Standard 2.0. (This includes .NET Framework 4.5.2)

.NET Standard 2.0 (which is in .NET Framework 4.6.1 and newer) is the minimum baseline for every dependency package in the Cirrus library and I can't really support versions of .NET Framework before 4.6.1 because it would break most of the features in the library. 

Multi-targeting is still in progress and will be in the next version of the library, but the minimum target version will be .NET Standard 2.0 (.NET Framework 4.6.1)

Apologizes for the inconvenience. 

Edit:

After taking a stab at backporting the library to .NET Standard 2.1, 2.0, & .NET FX 4.5.2, I'm reporting that the library will not support versions prior to .NET 5
